---
- hosts: all
- name: Ensure notepad++ is installed using chocolatey
  win_chocolatey:
     name: notepadplusplus
     state: present
     
- name: Create local admin and place it in Administrator group
  win_user:
     name: localadmin
     password: "xxxxxxxx"
     groups: ["Administrators"]
