# Virtual memory susceptible to exploitation when not randomized
# Identifier: (hardening_randomized_vm|RANDOMIZED_VM_HARDENING_2,105,fix)
# Version: 3f74744ce9b66c20b55f6dd4e580d77d7e7039b1
- name: Set kernel.randomize_va_space to 2
  hosts: all
  become: true
  tasks:

    - name: Set kernel.randomize_va_space parameter
      sysctl:
        state: present
        name: kernel.randomize_va_space
        value: 2
        sysctl_set: true

    - name: remove norandmaps from boot params
      command: '/sbin/grubby --update-kernel ALL --remove-args norandmaps'
      check_mode: false


# Decreased security in OpenSSH settings (LoginGraceTime)
# Identifier: (hardening_ssh_grace_time|OPENSSH_HARDENING_GRACE_TIME,105,fix)
# Version: 0c017d5047b027b9e640818bb8b82dc91c2d7476
- name: Set SSH LoginGraceTime to 1m
  hosts: all
  become: true
  tasks:
    - name: LoginGraceTime 1m
      lineinfile:
        backup: yes
        dest: /etc/ssh/sshd_config
        regexp: '(?i)^\s*LoginGraceTime'
        line: 'LoginGraceTime 1m'

    - name: restart sshd
      service:
        name: sshd
        state: restarted
