---
- hosts: all
  tasks:

  - name: Install firewalld 
    yum:
     name: firewalld
     state: present 
    
  - name: enable Firewalld
    service:
     name: firewalld
     state: started
     enabled: yes 

#  - name: reset firewalld to default 
#     file:
#       src:  /usr/lib/firewalld/zones/public.xml
#       dest: /etc/firewalld/public.xml

  - name: append standard services 
    firewalld:
     service: "{{ item }}"
     permanent: yes
     state: enabled
    with_items:
       - ldaps
       - kerberos
       - dns
       - ntp
       - ssh
    notify:
     - restart firewalld
 
  handlers:
      - name: restart firewalld
        service: 
           name: firewalld 
           state: restarted
