---
- hosts: localhost

  tasks:
  - name: Install Gluster 5
    yum_repository:
      name: glusterfs-5
      baseurl: http://buildlogs.centos.org/centos/7/storage/x86_64/gluster-5
      gpgcheck: no
      description: GlusterFS 5 YUM REPO
      state: present
      enabled: yes

  - name: Install Gluster
    yum:
      name: glusterfs-server
      state: present

