---
# create a new VM from a template

- name: VM from template
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        cluster: "{{ vm_cluster }}"
        datacenter: "{{ vm_datacenter }}"
        name: "{{ vm_name }}"
        template: "{{ vm_template }}"
        datastore: "{{ vm_datastore }}"
        networks:
        - name: "{{ vm_network }}"
          type: static
          ip: "{{ vm_ip_address }}"
          netmask: "{{ vm_ip_netmask }}"
          gateway: "{{ vm_ip_gateway }}"
        hardware:
          memory_mb: "{{ vm_memory_gb * 1024 }}"
          num_cpus: "{{ vm_cpu_count }}"
          num_cpu_cores_per_socket: 1
          hotadd_cpu: True
          hotremove_cpu: True
          hotadd_memory: True
        folder: "{{ vm_folder }}"
        resource_pool: "{{ vm_resource_pool }}"
        wait_for_ip_address: True
        state: poweredon
      register: newvm
