- name: Create VM from template
    vmware_guest:
      validate_certs: False
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      cluster: "{{ vm_cluster }}"
      datacenter: "{{ vm_datacenter }}"
      name: "{{ item.name }}"
      template: "{{ item.template }}"
      datastore: "{{ vm_datastore }}"
      customization:
        dns_servers:
          - 10.30.x.x
          - 10.30.x.x
        dns_suffix:
          - example.com
          - ad.example.com
        domain: exmaple.com
      networks:
      - name: "{{ vm_network }}"
        type: static
        ip: "{{ item.ip }}"
        netmask: "{{ item.netmask }}"
        gateway: "{{ item.gateway }}"
      hardware:
        memory_mb: "{{ vm_memory_gb * 1024 }}"
        num_cpus: "{{ vm_cpu_count }}"
        num_cpu_cores_per_socket: 1
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: True
      folder: "{{ vm_folder }}"
      resource_pool: "{{ vm_resource_pool }}"
      wait_for_ip_address: True
      state: poweredon
    register: newvm

  - debug:
      var: newvm

  - name: Add new VM to inventory
    add_host:
      hostname: "{{ item.name }}"
      ansible_host: "{{ item.ip }}"
      groups: NewVMs
