---
- hosts: web
  tasks:
  - name: Ensure IIS is installed
    win_feature: 
       name: Web-Server
       state: present
    when: ansible_os_family == "Windows" 
       
  - name: Deploy Index File
    template: 
       src: iisstart.j2
       dest: c:\inetpub\wwwroot\iisstart.html
